version: "3"
services:
  php-fpm:
    container_name: "php"
    build: "./php/extension"
    ports:
      - "9000:9000"
    volumes:
      - "./php/etc/php/php.ini:/usr/local/etc/php/php.ini"
      - "./php/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf"
      - "./php/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf"
      - "../back-end:/var/www/html"
      - "./php/log:/var/log/php"
      - "/etc/localtime:/etc/localtime"
    environment:
      - TZ=Asia/Shanghai
    restart: always
    networks:
      app_net:
        ipv4_address: 10.10.10.2
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "php-fpm"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "../back-end:/var/www/html"
      - "./nginx/log:/var/log/nginx"
      - "/etc/localtime:/etc/localtime"
    restart: always
    links:
      - php-fpm
    networks:
      app_net:
        ipv4_address: 10.10.10.3
  redis:
    image: redis:latest
    environment:
      - PORT=6379
      - TZ=Asia/Shanghai
    ports:
      - "6379:6379"
    stdin_open: true
    volumes:
      - "/etc/localtime:/etc/localtime"
    networks:
      app_net:
        ipv4_address: 10.10.10.4
networks:
  app_net:
    ipam:
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1

